[variables]
VITE_BASE_PATH = "/"

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build -- --base=/"]

[start]
cmd = "npx -y serve -s dist -l $PORT"
